name: hionepedia
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  animated_notch_bottom_bar: ^1.0.0
  dio: ^5.2.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  model_viewer_plus: ^1.5.0
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/model/
